# This function will be called when the user invokes
# the New Project wizard using the project template defined in the template file
# at:
#
#   inst/rstudio/templates/project/PCMP_rstudio_template.dcf

setup_files <- function(path, ...) {

  # ensure path exists
  dir.create(path, recursive = TRUE, showWarnings = FALSE)

  # generate header
  header <- c(
    "# This file was generated by a call to 'PCMPrstudiotemplate::setup_files()'.",
    "# The following inputs were received:",
    ""
  )

  # collect inputs
  dots <- list(...)
  text <- lapply(seq_along(dots), function(i) {
    key <- names(dots)[[i]]
    val <- dots[[i]]
    paste0(key, ": ", val)
  })

  prj_name <- dots["prj_name"]
  prj_type <- dots["prj_type"]

  # collect into single text string
  contents <- paste(
    paste(header, collapse = "\n"),
    paste(text, collapse = "\n"),
    sep = "\n"
  )

  # write to log file
  writeLines(contents, con = file.path(path, "creation_log"))

  rmarkdown::draft(paste0(prj_name,".Rmd"), template = "template-name", package = "basicTemplate", edit = F, create_dir = T)

  if(prj_type == "16S") {
    temp <- readLines(con = file.path(prj_name,"mother_qiime2_TagSequencingReport.Rmd"))
    actual_report <- paste(
      paste(contents, collapse = "\n"),
      paste(temp, collapse = "\n"),
      sep = "\n"
    )
    writeLines(actual_report, con = file.path(path, paste0(prj_name,".Rmd")))
  }

  if(prj_type == "WGS") {
    temp <- readLines(con = file.path(prj_name,"mother_shotgun_report.Rmd"))
    actual_report <- paste(
      paste(contents, collapse = "\n"),
      paste(temp, collapse = "\n"),
      sep = "\n"
    )
    writeLines(actual_report, con = file.path(path, paste0(prj_name,".Rmd")))
  }

  #copy all the supporting files from the template
  system(paste0("cp -R -n ", file.path(prj_name), "/* ", file.path(path)), wait = T)
  #file.copy(from = file.path(prj_name), to = file.path(path),
  #          recursive = T, overwrite = F)

  #remove the originals (unless you want a lot of unnecessary clutter!)
  #system(paste0("rm -rf ", file.path(prj_name)))
  unlink(file.path(prj_name), recursive = T, force = T)

  #apologies for using a mix of base R and a system command for these two
  #couldn't get the file.copy to work nicely for me

}
